#!/usr/bin/env python3
from pexpect import replwrap
import subprocess

prompt="rholang $ "
#prompt2="root@jcode:~/code/rchain#"
#cmd = "sudo docker run --rm -it -v /tmp/a:/var/lib/rnode --cpus=.5 --memory=1024m --name rnode-repl --network testnet1.rchain coop.rchain/rnode:latest --grpc-host node0.testnet1.rchain -r"
cmd = "sudo docker run --rm -it -v /tmp/a:/var/lib/rnode --cpus=.5 --memory=1024m --name rnode-repl --network testnet1.rchain rchain/rnode:dev --grpc-host node0.testnet1.rchain -r"

subprocess.run(["docker", "container", "rm", "-f", "rnode-repl"])


py = replwrap.REPLWrapper(cmd, prompt, None)
for i in range(1000):
   print(i)
   a = py.run_command("5")
   print(a)
